"""add input_output_tokens_to_official_keys

Revision ID: ddb8814b35c9
Revises: a6b8ff377278
Create Date: 2025-12-01 22:10:23.716046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb8814b35c9'
down_revision: Union[str, Sequence[str], None] = 'a6b8ff377278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_keys', sa.Column('input_tokens', sa.BigInteger(), nullable=True))
    op.add_column('official_keys', sa.Column('output_tokens', sa.BigInteger(), nullable=True))
    op.drop_column('official_keys', 'total_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_keys', sa.Column('total_tokens', sa.BIGINT(), nullable=True))
    op.drop_column('official_keys', 'output_tokens')
    op.drop_column('official_keys', 'input_tokens')
    # ### end Alembic commands ###
